name = "classroom-api"
main = "src/index.js"
compatibility_date = "2024-03-20"

[[d1_databases]]
binding = "DB"
database_name = "classroom_db"
database_id = "e9d7b401-c5b9-40d9-8ed6-ae063dffc0a0" # User will fill this in
